In [7]:
%matplotlib inline

In [8]:
from matplotlib import pyplot as plt

In [9]:
import os
import pickle
import numpy as np
from scipy import sparse
from functools import partial
from sklearn.externals import joblib
from sklearn.cross_validation import KFold
from sklearn.metrics import confusion_matrix
from sklearn.cross_validation import train_test_split
import seaborn as sns
import pandas as pd
from sklearn.linear_model import RidgeClassifier

In [10]:
labels = joblib.load("/home/jovyan/persistent_data/data/dumps/labeled_corpus_labels.pkl")
features = joblib.load("/home/jovyan/persistent_data/data/dumps/labeled_corpus_matrix.pkl")
features = features.todense()
mozart_labels = [k for k in range(len(labels)) if labels[k] == "mozart"]
bach_labels = [k for k in range(len(labels)) if labels[k] == "bach-js"]
schubert_labels = [k for k in range(len(labels)) if labels[k] == "schubert"]
chopin_labels = [k for k in range(len(labels)) if labels[k] == "chopin"]
tchaikovsky_labels = [k for k in range(len(labels)) if labels[k] == "tchaikovsky"]
X = features[mozart_labels + bach_labels + schubert_labels + chopin_labels + tchaikovsky_labels].A
y = np.array([0 for i in range(len(mozart_labels))] + [1 for i in range(len(bach_labels))] + 
            [2 for i in range(len(schubert_labels))] + [3 for i in range(len(chopin_labels))] +
            [4 for i in range(len(tchaikovsky_labels))])
y = y.reshape((y.shape[0],))
del features

In [11]:
X = X[:,X.sum(axis=0).nonzero()[0]]

In [53]:
regularization_parameter = 10000.0
predicted = []
actuals = []
lr_models = []
i = 0
for train_idx, test_idx in KFold(n=X.shape[0], n_folds=5, shuffle=True):
    X_train = X[train_idx]
    y_train = y[train_idx]
    X_test = X[test_idx]
    y_test = y[test_idx]
#     p = [1/np.bincount(y_train)[i] for i in y_train]
#     undersample_idx = np.random.choice(np.arange(X_train.shape[0]),
#                  size=np.bincount(y_train).min() * len(set(y_train)),
#                  p=p / sum(p))


    lr = RidgeClassifier(alpha=regularization_parameter)
    
    try:
        lr.fit(X_train, y_train)
    except:
        continue
#     preds = (lr.predict_probabilities(X_test) > 0.5).astype(int)
#     predicted.append(preds)
#     actuals.append(y_test)
#     lr_models.append(lr)
#     pickle.dump(lr_models, open("./dumps/logistic/normal/model_fold_{fold}_reg_{reg}.pkl"
#                                 .format(fold=str(i), reg=str(regularization_parameter)), 'wb'))
#     pickle.dump(predicted, open("./dumps/logistic/normal/predicted_fold_{fold}_reg_{reg}.pkl"
#                                 .format(fold=str(i), reg=str(regularization_parameter)), 'wb'))
#     pickle.dump(actuals, open("./dumps/logistic/normal/actuals_fold_{fold}_reg_{reg}.pkl"
#                                 .format(fold=str(i), reg=str(regularization_parameter)), 'wb'))
#     i += 1

In [54]:
from sklearn import metrics

In [55]:
print(metrics.accuracy_score(y_test, lr.predict(X_test)))
print(metrics.confusion_matrix(y_test, lr.predict(X_test)))

0.774834437086
[[ 64  63   0   1   0]
 [  8 459   0   0   0]
 [ 11  16  22   5   5]
 [  2  24   3  22   0]
 [  0  25   2   5  18]]
